apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      
      # CRITICAL: This enriches logs with Kubernetes metadata
      # Pod name, namespace, labels, node name — all added automatically
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
        
        # Only collect logs from boutique-app namespace
        # Prevents noise from kube-system, monitoring etc.
        - drop_event:
            when:
              not:
                equals:
                  kubernetes.namespace: "boutique-app"

    output.logstash:
      hosts: ["logstash.logging.svc.cluster.local:5044"]
      
    # Send Filebeat's own metrics to Elasticsearch
    monitoring.enabled: false 