{{- if .Values.configData -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm

data:
  {{- range $key, $value := .Values.configData }}
  "{{ $key }}": {{ $value | quote }}
  {{- end }}
{{- end }}