apiVersion: v1
kind: ServiceAccount
metadata:
  # Links the identity to the specific microservice name
  name: {{ .Values.serviceName }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    # Used for IAM Roles for Service Accounts (IRSA) in EKS
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
# Recommended for security: do not auto-mount API tokens if not needed
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default false }}