# ansible/inventory/hosts.yml
all:
  hosts:
    localhost:
      ansible_connection: local  # Runs locally using your kubeconfig
      ansible_python_interpreter: /usr/bin/python3
  
  vars:
    # These get populated from Terraform outputs
    eks_cluster_name: "boutique-app-dev-cluster"
    aws_region: "ap-south-1"
    aws_account_id: "889501007925"
    environment: "dev"
    domain_name: "rohandevops.co.in"