# --- environments/prod/backend.conf ---

# Dedicated Production S3 Bucket
# Industry Standard: This bucket should have 'MFA Delete' enabled for max security
bucket = "rohan-terraform-state-prod"

# The path to the production state file
# Isolated from dev/ to prevent cross-environment state corruption
key = "prod/terraform.tfstate"

# The AWS region for the state infrastructure
region = "ap-south-1"

# Dedicated Production DynamoDB table for State Locking
# Ensures only one production deployment can happen at a time
dynamodb_table = "terraform-lock-prod"

# Mandatory encryption for production state files
encrypt = true