apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adservice
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: online-boutique

  source:
    repoURL: https://github.com/rohandeb2/11-microservices-webapp-2.git
    targetRevision: HEAD
    path: k8s-boutique-chart

    helm:
      valueFiles:
        - env-values/adservice.yaml

      parameters:
        - name: serviceName
          value: adservice
        - name: image.tag
          value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: boutique-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - SkipDryRunOnMissingResource=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: adservice
#   namespace: argocd
#   # CEO Note: Finalizers ensure that if you delete this app from ArgoCD, 
#   # it cleans up the K8s resources instead of leaving orphans.
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   # Senior DevOps Fix: Point to the production project we created
#   project: online-boutique

#   source:
#     repoURL: https://github.com/rohandeb2/11-microservices-webapp-2.git
#     targetRevision: HEAD
#     path: k8s-boutique-chart
    
#     helm:
#       # Inject the service-specific values from your env-values folder
#       valueFiles:
#         - ../../env-values/adservice.yaml
      
#       # 12 LPA Standard: Override parameters dynamically
#       parameters:
#         - name: "serviceName"
#           value: "adservice"
#         - name: "image.tag"
#           value: "v2" # Using the fixed build to resolve the /app/bin/adservice error

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: boutique-app

#   syncPolicy:
#     automated:
#       prune: true      # Remove resources if they are deleted from Git
#       selfHeal: true   # Revert manual kubectl edits to match Git
#     syncOptions:
#       - CreateNamespace=true
#       - SkipDryRunOnMissingResource=true
    
#     # Critical for EKS Fargate: Handle slow node provisioning
#     retry:
#       limit: 5
#       backoff:
#         duration: 10s
#         factor: 2
#         maxDuration: 5m